### ISSUE TITLE
Adding an audio sample for examples

### ISSUE THREAD

**Issue by sjfricke** [tinyalsa/tinyalsa#100]
As is the pcm-readi.c example just seg faults since there isn't anything to read in. I understand the idea of just showing the example, but thoughts of me adding a small demo wav file so it's working right off the back.

Also there are a few sample audio tracks in `/usr/share/sounds/alsa` already

**Comment by tay10r** [comment]
I like the idea of adding a sample audio track.

I'm not quite sure if the sounds you mentioned depend on a standard ALSA package being installed. If they do, I'd prefer to include one or two (as needed) directly in the repository.

I'll take a look into why they're seg faulting.

**Comment by sjfricke** [comment]
Sounds good, I was assuming we add it to the repo so its there no matter what and it won't add to much weight the repo overall size

**Comment by tay10r** [comment]
@sjfricke agreed. I believe SoX does the same.

**Comment by sjfricke** [comment]
Also I think it is seg faulting since I don't have any valid PCM in according to `tinypcminfo`

**Comment by tay10r** [comment]
I'll take a look at the seg fault. Do you have a short clip you could add as an example?

**Comment by tay10r** [comment]
Fixed the segmentation fault in commit 1a12af92a71dbad28e08ba3d0ee0e040331835b8 in the development branch. It'll merge with the master branch in the next release.

**Comment by tay10r** [comment]
Segmentation fault was fixed in f40bda8.
