### ISSUE TITLE
Question about license.

### ISSUE THREAD

**Issue by Taejun-Kwon** [tinyalsa/tinyalsa#103]
Hello.
I have question about tinyalsa.
Actually tinyalsa using BSD license, but it use some structurs and constant values in ALSA.
I checked ALSA's license but it is LGPL. 
As I know even if anything uses constant value in spechfic file which is under the GPL, it can not apply BSD.
If I fork tinyalsa and modify something to do not use ALSA, can I keep BSD license??
Could you please let me know it?
Thank you so much.

**Comment by tay10r** [comment]
I'm not quite sure what you're asking. If you fork TinyALSA, you have to keep the license it's under currently - which is BSD.
