### ISSUE TITLE
pcm_read blocking

### ISSUE THREAD

**Issue by FeeiSZ** [tinyalsa/tinyalsa#110]
Hi,tay10r
  My program have a A few seconds  blocking (Read buf time is 20ms) when "pcm_read" first called. And subsequent call run normally. 
  what might be the cause of this BUG?

**Comment by tay10r** [comment]
I haven't heard of that happening before. Can you send a minimal example that reproduces the bug?

**Comment by tay10r** [comment]
@FeeiSZ I'm closing this issue since you aren't responding. Open this issue again if you can show me how to reproduce this problem of yours.
