### ISSUE TITLE
How to route audio through digital microphone using tinymix

### ISSUE THREAD

**Issue by pkalebu** [tinyalsa/tinyalsa#114]
What exact modules should be set through tinymix to correctly capture input from an external digital microphone?

**Comment by tay10r** [comment]
What modules are you taking about exactly? The `tinymix` program accesses and modifies mixer controls. The program you'd use to capture input from a microphone would be `tinycap`. Specifying the microphone to record from usually involves specifying the card and device number, assuming the microphone is not the default input for the system.

**Comment by pkalebu** [comment]
Got it. By modules I mean mixer controls. I am unsure which ones to modify and how exactly to modify them. Is there a reference for how to know which controls to modify?

**Comment by tay10r** [comment]
Not to my knowledge. I believe most of the controls are named by the vendors (but I could be wrong), therefore there's not much standardization about it. Most of the controls that `tinymix` is able to modify, you can also modify in some other GUI program, if that makes it easier.

I guess in your case, make sure your microphone isn't muted and that the volume is up to a normal level. You should be able to do this with `tinymix` or your desktop environment (if you have one.)

**Comment by pkalebu** [comment]
Makes sense, thank you!

**Comment by tay10r** [comment]
I'm closing the issue but feel free to raise another issue if you have a problem with one of the programs (or the API.)
