### ISSUE TITLE
How to build for Android?

### ISSUE THREAD

**Issue by DevRonin** [tinyalsa/tinyalsa#116]
How to build for Android?

**Comment by tay10r** [comment]
The most straightforward way is to use the Android build system. Android has its own TinyALSA repository that hasn't pulled from this one in some time.

You can find it at https://android.googlesource.com/platform/external/tinyalsa/

**Comment by DevRonin** [comment]
I manage to build using lineageos build instruction (some changes in order to compile tinycap and tinymix, by default only tinyplay binary is included) 
Lineageos is  using this repo:
https://github.com/LineageOS/android_external_tinyalsa
Seem to be a older version, what will be the drawbacks?

Any documentation on how to use tinymix ?

**Comment by tay10r** [comment]
Yes, there's a manual page for tinymix.

```
man -l utils/tinymix.1
```

The only drawback is that there are missing features (and probably PCM formats) to using the older version. I'm also pretty sure that there are no manual pages in the older version. The interface of `tinymix` is quite different in the older versions of TinyALSA. This version is based on the `amixer` utility.
