### ISSUE TITLE
 Android 5.0 and later only support position-independent executables(-fPIE)

### ISSUE THREAD

**Issue by sajid-verveba** [tinyalsa/tinyalsa#119]
i have genrated exutables using tinyalsa release 1.1.1 with command ndk-build inside jni folder.
I have copied tinymix in /data/local/tmp, also set chmod 777 to tinymix file.

After running tinymix command on device i got following errror:

`"/data/local/tmp/tinymix": error: Android 5.0 and later only support position-independent executables (-fPIE).`

**Comment by tay10r** [comment]
Does it help adding `LDFLAGS += -fpir` to `utils/Makefile`?

**Comment by tay10r** [comment]
Alright, thanks for that info. I added those flags to the compiler flags and linker flags. If you pull the latest changes, you should be able to give it a shot.

**Comment by tay10r** [comment]
@sajid-verveba Did this fix your issue?

**Comment by tay10r** [comment]
I verified that the executables run now using termux and clang. You can  open another issue if the problem persists.
