### ISSUE TITLE
Clarification regarding Usage on Android

### ISSUE THREAD

**Issue by schmidh** [tinyalsa/tinyalsa#133]
Hi Taylor,

sorry for asking some very basic questions regarding tinyalsa. I'm not having real issues with the software, just need to know the applicability of it on Android:

Is it possible to use tinyalsa for capturing any audio on Android devices? A typical use case would be an audio visualizer. What would be the prerequsites? Is rooting the device necessary?

Very kind regards,
Hans-J.

**Comment by tay10r** [comment]
Hey! I have no problem answering questions on the project. Sorry for the delayed response, I could've sworn that I responded to this.

**It is possible to use tinyalsa for capturing any audio on Android devices?**

Yes, it's already used by Android to do this. TinyALSA is not normally used by end-point applications to record audio, it's primarily used by the Android operating system. Applications typically record audio through the Java API. There's several layers between the application and TinyALSA.

**A typical use case would be an audio visualizer. What would be the prerequisites?**

If you're developing for Android, I would suppose that you'd be experienced in developing Android apps. In any case, you'd want to know generic audio development concepts. This includes, and not limited to:

 - Sampling rate
 - Sample formats
 - Overruns and underruns

If you're going to use TinyALSA directly, it will typically require root access to the phone. For example, if you're using Termux, you can't normally access any of the PCM device paths. If you drop into a root terminal, you can access them. But this may not be the route you'd want to take. You don't have to have root access to record audio on an Android device (if you use the Android API.)

Does this clarify your understanding?

**Comment by schmidh** [comment]
Yes, this helps me a lot. Thank you very much for your detailed information!
