### ISSUE TITLE
Proposal for extending tinyalsa to support plugins

### ISSUE THREAD

**Issue by gajare-codeaurora** [tinyalsa/tinyalsa#135]
Current tinyalsa supports only interfacing directly with the ALSA kernel interface. Proposal is to add support for tinyalsa plugins for below reasons:
• Allow custom implementation of PCM and mixer modules in userspace
• Plugins can perform data processing (ex: noise suppression, etc)
• Plugins can enable software enhancements (ex: channel mixer, rate convertors, etc)
• Can extend hardware capabilities (ex: DSP not having enough MIPS, etc)

To add this support, we have come up with the below design goals to make sure the impact is minimal and the changes are helpful to the community of tinyalsa users.
• Extend tinyalsa functionality at run time to support plugins
• No change in any of the APIs exposed by tinyalsa
• Re-use all existing tinyalsa functionality for plugins
• Do not allow duplication of similar logic
• Plugins to adhere to same ALSA kernel interface (from uapi/asound.h file)

The high level design to achieve this is as described below, request you to please let us know if you have any other options in mind that can better the design, we are open to changes that will benefit the community
• Concept of virtual PCM nodes and mixer nodes
• Virtual nodes defined in config file
• At [pcm|mixer]_open call, resolve the node to be either kernel node (present under /dev/snd/*) or as a virtual node (defined in the config file).
• Based on resolution at open assign function pointers for all functions at kernel interface level (ex: read/write/ioctl, etc).
• For kernel node, all function pointers implemented under new file pcm_hw.c and all of them call into the kernel interface
• For virtual node, all function pointers implemented under new file pcm_plugin.c, which interfaces with the plugin.
• Plugin itself is a .so library, dynamically dlopen’ed by the pcm_plugin.c at open, and expected to register its ops to the framework (ex ops: open/read/write/hw_params, prepare, etc)

**Comment by tay10r** [comment]
Suppose that somebody wants to write their own virtual PCM or mixer library. They'd go about writing and generating a library, which we'll call `example-pcm.so`.

Do they have to edit a single config file to get their plugin recognized? This might make it somewhat difficult for a plugin to be automatically installed through a script.

Or is it a directory in which config files go into, such as `/path/to/pcm-configs.d/*.conf` or `/path/to/mixer-configs.d/*.conf`, which is easier to install to.

How does one go about installing their plugin?

**Comment by tay10r** [comment]
Closed by #137
