### ISSUE TITLE
useage for tinymix？

### ISSUE THREAD

**Issue by dex7erhan** [tinyalsa/tinyalsa#139]
#tinymix
Mixer name: 'sdm660-snd-card-mtp'
Number of controls: 2288
ctl	type	num	name                                     value
0	INT	3	Voice Rx Device Mute                     -1 -1 -1
3	INT	3	Voice Rx Gain                            -1 -1 -1
4	ENUM	1	TTY Mode                                 OFF
5	INT	2	Slowtalk Enable                          -1 -1
9	BOOL	1	Voice Sidetone Enable                    Off
12	INT	1	Voip Mode Config                         12

how to reset the value of “Voice Rx Gain”？
input "tinymix  ”Voice Sidetone Enable” 1 "，it works.
but input "tinymix  “Voice Rx Gain” 0 0 0"，
I only got this error message: 
"Error: only enum types can be set with strings."
so how to reset this value?By modifying the xml files in /system/etc?
If there is an usage , it would be nice for some newbee like me. thanks.

**Comment by tay10r** [comment]
What is the output of `tinymix --version`? Google has an outdated version of the project in their repositories, it's possible you're using that one.

**Comment by dex7erhan** [comment]
R11s:/ # tinymix -version
Invalid mixer control

...

**Comment by tay10r** [comment]
@dex7erhan Sorry for the delay! I thought I had responded to this. The `version` option was added three years ago, and it appears version of the program doesn't recognize it. It's very likely that you're using an outdated version of the project. There's not much I can do about that.
