### ISSUE TITLE
con't played the end of buff

### ISSUE THREAD

**Issue by muxi01** [tinyalsa/tinyalsa#152]
I met the problem,when i use tinyplay to play sine wav file, and test the line out.the end of wave was killed.

**Comment by muxi01** [comment]
thanks for your reply,The wav file generate by cool edit pro,use the feature of 'fate in'  to decorate wave head,and use 'fate out' to decorate wave tail.the whole wave has not a long content of silence.
copy of file follow this words,plaese downloading,then  rename sound9.wav.zip to sound9.wav
[sound9.wav.zip](https://github.com/tinyalsa/tinyalsa/files/4513785/sound9.wav.zip)
![P1](https://user-images.githubusercontent.com/23053634/79940345-0f9a0600-8494-11ea-885b-0b58e4a8e554.png)

**Comment by tay10r** [comment]
I was able to successfully play this file, but I had to convert the tile to use 2 channels first. Maybe that's your issue? You can give it a shot using `sox`.

```
mv sound9.wav.zip sound9.wav
sox sound9.wav sound9_stereo.wav channels 2
./tinyplay sound9_stereo.wav
```

None of the utilities handle mono-to-stereo conversion, so that may be the issue. Let me know if converting to stereo fixes your problem.

**Comment by muxi01** [comment]
thanks very much for your seriously,Maybe its my mistake of cannot write clear.I used the same way as your,i can hear the sounds in the alsaplay playing.but i tested the wave of line out by oscilloscope. it captured wave on first picture, we could see the wave has not complete.
when i used cool Edit Pro to play, i can get a whole wave on the screen of oscilloscope(second picture).

![P_abnormal](https://user-images.githubusercontent.com/23053634/79967870-f9a33a00-84c1-11ea-8850-439469f9f94c.jpg)
![P_normal](https://user-images.githubusercontent.com/23053634/79967888-00ca4800-84c2-11ea-90c0-3c969afb187a.jpg)
![P_shown](https://user-images.githubusercontent.com/23053634/79967901-058efc00-84c2-11ea-8b4a-f0312abfb1d8.png)

**Comment by tay10r** [comment]
I see what you're saying now. Let me spend some time and see if I can reproduce this somehow. I don't have an o-scope but I might be able to get some data with a VM or something.

**Comment by muxi01** [comment]
ok,thanks! good luck to you

**Comment by tay10r** [comment]
While I still haven't finished a script to test audio with, I did add a wait call to the end `tinyplay` which may fix the issue. Can you give it a test?

**Comment by muxi01** [comment]
i tried the same way as you,but it does not work,the newerst problem is up,that a little of sounds are repeat or generate by player.please look and see 
![P2](https://user-images.githubusercontent.com/23053634/80328274-7000bd00-8871-11ea-9564-d09566f125cc.png)

modify contents  were these:

int play_sample(struct ctx *ctx)
{
    char *buffer;
    int size;
    int num_read,now;
    struct timeval current_time;
    size = pcm_frames_to_bytes(ctx->pcm, pcm_get_buffer_size(ctx->pcm));
    buffer = malloc(size);
    if (!buffer) {
        fprintf(stderr, "unable to allocate %d bytes\n", size);
        return -1;
    }

    /* catch ctrl-c to shutdown cleanly */
    signal(SIGINT, stream_close);

    do {
        num_read = fread(buffer, 1, size, ctx->file);
        if (num_read > 0) {
		if (pcm_writei(ctx->pcm, buffer,
			pcm_bytes_to_frames(ctx->pcm, num_read)) < 0) {
                fprintf(stderr, "error playing sample\n");
                break;
            }
        }
    } while (!close_flag && num_read > 0);

    gettimeofday(&current_time,NULL);
    now = current_time.tv_sec + current_time.tv_usec / 1000;
    fprintf(stderr, "1.pcm_drain at here curtime=%d\n",now);
    pcm_drain(ctx->pcm);
     
    gettimeofday(&current_time,NULL);
    now = current_time.tv_sec + current_time.tv_usec / 1000;
    fprintf(stderr, "2.pcm_drain at here curtime=%d\n",now);

    sleep(1);
    free(buffer);    
    return 0;
}

int pcm_drain(struct pcm *pcm)
{
	/* lock handled in the callback */
    if (pcm->ops->ioctl(pcm->data, SNDRV_PCM_IOCTL_DRAIN) < 0)
        printf("cannot drain pcm\n");
        ///return oops(pcm, errno, "cannot stop channel");
    return 0;
}

**Comment by tay10r** [comment]
Alrighty thanks for the update!

**Comment by muxi01** [comment]
maybe this issue is still exist,could you continue to solve it? 
 that is noise occurred follow the end of playing.

**Comment by dvdli** [comment]
We have added a check of the wave data size. Could you try this with the newest version again?

**Comment by dvdli** [comment]
Please feel free to re-open this issue if there is any new problem. Thanks!
