### ISSUE TITLE
Is the tinyALSA has any hook function?

### ISSUE THREAD

**Issue by jerryyyq** [tinyalsa/tinyalsa#167]
Is the tinyALSA has any function can hook and capture device playback data?
Thanks.

**Comment by tay10r** [comment]
There's no function that exists to do that. If you're talking about recording playback data from another process, then it isn't in the scope of this library to do that.

**Comment by jerryyyq** [comment]
I don't think so.
Because ALSA have somd pcm_hook functions, why tinyALSA not support?

**Comment by tay10r** [comment]
Unless you're talking about a simple function pointer in an output PCM, supporting PCM hook functions from alsa-lib requires handling their configuration files. The whole purpose of TinyALSA was to use the audio devices without having to support the whole asound.conf setup. I **think** you can still try to use loopback devices, but I'm not sure to be honest.
