### ISSUE TITLE
tinymix: set volume with percentages and increments

### ISSUE THREAD

**Issue by E5ten** [tinyalsa/tinyalsa#168]
Would it be possible to add functionality to do things like:
`tinymix set <volume control> 50%`
and
`tinymix set <volume control> 5+`
and combinations of the two? that way instead of having to know the range for the volume to do things like binding volume keys to increase or decrease volume by e.g. 5%, one could just bind them to something like:
`tinymix set <volume control> 5%+` or the same with 5%-.

**Comment by tay10r** [comment]
Wouldn't the `+` or `-` make more sense at the beginning of the value?

**Comment by tay10r** [comment]
I just pushed a completely untested commit for this. Please tell me if it works! Sorry, just got really busy and wasn't able to test it out.

**Comment by E5ten** [comment]
It's not working for me, the issues are that when I use one of these characters at the beginning the volume just gets set to 0, % and - or + can't be used together (doing +%num gives "only enum types can be set with strings"), the % is at the beginning when it would make more sense at the end, and the reason for `+` or `-` being at the end, when like you said they'd make more sense at the beginning, is that when you use `-` it'll be detected as an option.

**Comment by E5ten** [comment]
http://ix.io/2s62 this patch fixes some of the issues, for starters it switches `+` and `-` to be at the end instead of the beginning because of the problem with that I mentioned in the last comment, it also has `%` working correctly at the end (or 1 away from the end if there's a `+` or `-` following it), incrementing and decrementing still isn't working (`tinymix set <control> 10%-` just sets it to 10%), but the use of percentages is working with this.

**Comment by E5ten** [comment]
from what I can tell, the `has_sign` member isn't being used, after `out.value *= sign;` happens if `has_sign` is true `out.value` needs to be added to the original value so it modifies so it adds or subtracts instead of just being the new value.

**Comment by tay10r** [comment]
I meant just `-` and `+` at the beginning. The percent sign should definitely stay at the end. Let me do some research and see how other programs usually do it, so I can try to make it consistent. It looks like `amixer` does it the way you mentioned, so I'm leaning towards doing it that way.

I'll revisit that code right now. I literally just checked if it compiled, so I'm not surprised if it had issues.

**Comment by E5ten** [comment]
http://ix.io/2s67 this seems to make it work completely, and I understood you meant having `%` at the end, it's just that the code wasn't working that way in some places (is_int checked for a leading '%', not a trailing one, so the `%` was left in `*end` and lead to is_int returning false)

**Comment by E5ten** [comment]
Thanks for working on this so quickly by the way.

**Comment by tay10r** [comment]
@E5ten Of course! I'm not sure how much longer I'll be the maintainer for this project, but I'd like to leave it for the next person it a somewhat maintainable state.

Out of curiosity, where is that patch coming from?

**Comment by E5ten** [comment]
I made it.

**Comment by tay10r** [comment]
Ah, okay neat. Just pushed a commit to fix the last one. It seems to be working. I'll leave this issue open for a bit in case there's any issues with it.

**Comment by E5ten** [comment]
Sounds good, thanks for adding this, that was all I needed to switch from amixer to tinymix for my keybinds.

**Comment by tay10r** [comment]
Closing this since there doesn't seem to be any issues with it.
