### ISSUE TITLE
pcm_get_latency not implemented

### ISSUE THREAD

**Issue by apo72** [tinyalsa/tinyalsa#17]
service in available at API level(asoundlib.h) is not supported.

Should be something like that

unsigned int pcm_get_latency(struct pcm *pcm)
{
       unsigned int ret;
       signed long *latency;
       if(!pcm)
           return -1;
       if(ioctl(*(int *)pcm, SNDRV_PCM_IOCTL_DELAY, latency)) {
          return -1;
       }
       else 
          return ((unsigned int) latency);
       }
}

**Comment by tholberton** [comment]
Closing this issue, it was fixed by 9ecb93fb a couple of years ago (see `pcm_get_delay`).
