### ISSUE TITLE
Issue "ioctl err" with Debian.

### ISSUE THREAD

**Issue by iDalink** [tinyalsa/tinyalsa#170]
I test tinyalsa playing with Debian distribution.
My test command is `./tinyplay -d 0 friend.wav`.
And `ls /dev/snd` list files:
> ➜  utils git:(master) ✗ ls /dev/snd  
> by-path  controlC0  midiC0D0  pcmC0D0c  pcmC0D0p  pcmC0D1p  seq  timer

But I got an error with call `pcm->ops->ioctl(pcm->data, SNDRV_PCM_IOCTL_HW_PARAMS, &params)` in pcm_set_config, and  got errno 22.

I print `config` variable in ctx_init before pcm_open:

    printf("config channel:%d rate:%d perod:%dx%d formate:%d start:%d stop:%d silence:%d\n",
           config.channels, config.rate, config.period_size, config.period_count,
           config.format, config.start_threshold, config.stop_threshold, config.silence_threshold);
Log:
   config channel:1 rate:16000 perod:1024x2 formate:0 start:1024 stop:2048 silence:2048

**Comment by tay10r** [comment]
Okay, start by messing around with your config.

What is the output of `./tinypcmconfig`? You can to make sure, in particular, that your channels and your sampling rate are supported by the device.

**Comment by iDalink** [comment]
Well, is `./tinypcmconfig` build output? Only four commands exist in `utils` directory without `./tinypcmconfig`.

```
➜  utils git:(master) ✗ ls
friend.wav  meson.build  tinycap    tinycap.c  tinymix    tinymix.c  tinypcminfo    tinypcminfo.c  tinyplay    tinyplay.c  tinywavinfo.c
Makefile    optparse.h   tinycap.1  tinycap.o  tinymix.1  tinymix.o  tinypcminfo.1  tinypcminfo.o  tinyplay.1  tinyplay.o

```
`./tinypcminfo` output:
```
➜  utils git:(master) ✗ ./tinypcminfo          
Info for card 0, device 0:

PCM out:
      Access:	0x000009
   Format[0]:	0x000006
   Format[1]:	00000000
 Format Name:	U8, S16_LE
   Subformat:	0x000001
        Rate:	min=4000Hz	max=48000Hz
    Channels:	min=1		max=2
 Sample bits:	min=8		max=16
 Period size:	min=16		max=65536
Period count:	min=1		max=1024

PCM in:
      Access:	0x000009
   Format[0]:	0x000006
   Format[1]:	00000000
 Format Name:	U8, S16_LE
   Subformat:	0x000001
        Rate:	min=4000Hz	max=48000Hz
    Channels:	min=1		max=2
 Sample bits:	min=8		max=16
 Period size:	min=16		max=65536
Period count:	min=1		max=1024

```

**Comment by iDalink** [comment]
> Okay, start by messing around with your config.
> 
> What is the output of `./tinypcmconfig`? You can to make sure, in particular, that your channels and your sampling rate are supported by the device.

**Comment by tay10r** [comment]
Sorry, I meant to write `tinypcminfo`. Did you get this fixed? Was the sampling rate the issue?

**Comment by iDalink** [comment]
My audio file`s rate is 16000. It fit to audio card rate range `4000~48000`. I have none ideal about the issue.

**Comment by tay10r** [comment]
Is there any other audio files that work? What happens when you capture data with `tinycap`? What is the audio format?

**Comment by iDalink** [comment]
I used `ps` command to find out doubtful proccess. `Pulseaudio` is stopped definitely. Did not find doubtful proccess yet.

**Comment by iDalink** [comment]
After messing try, I found only 48000 simple rate works fine.  It might be driver bug.
