### ISSUE TITLE
Bug in tinymix util

### ISSUE THREAD

**Issue by rohkkumar** [tinyalsa/tinyalsa#171]
For TLV mixer controls, tinymix adds TLV_HEADER_SIZE to the num_values and sets 0th and 1st element of tlv to 
tlv[0] = 0;
tlv[1] = num_values;
before calling mixer_ctl_set_array(). 
https://github.com/tinyalsa/tinyalsa/blob/master/utils/tinymix.c#L281

However, mixer_ctl_set_array() also does the same thing
https://github.com/tinyalsa/tinyalsa/blob/master/src/mixer.c#L1088

This causes TLV header to be added twice. I already have a fix but wanted to confirm if I am missing something here.

**Comment by tay10r** [comment]
I think I agree with you but I want to look at it in a debugger before I say anything for certain.
When reviewing that code I found an additional issue in the mixer API that I should probaby address first.

**Comment by rohkkumar** [comment]
@tay10r , Did you got a chance to look into the issue?

**Comment by tay10r** [comment]
@rohkkumar Yes, I'm still looking into it. It looks like there might be a couple of other spots where the TLV gets counted twice. For instance, here: https://github.com/tinyalsa/tinyalsa/blob/fd59e16f1893d8b49b0fae421d09df7161b52616/src/mixer.c#L977 When it is clearly expected that the TLV is already accounted for at this line: https://github.com/tinyalsa/tinyalsa/blob/fd59e16f1893d8b49b0fae421d09df7161b52616/src/mixer.c#L953
If you have a patch you already have ready, then I'd be happy to accept it. The root of the issue I think is that there should be better documentation on when and when not to include the TLV size. Right now, it looks like you omit it for writes and include it for reads. I think it should probably be the same for both reading and writing, but I don't think that's something that can be changed and maintain backward compatibility.
