### ISSUE TITLE
TLV_HEADER_SIZE is added to num_values in tinymix.c

### ISSUE THREAD

**Issue by simonrules** [tinyalsa/tinyalsa#175]
TLV_HEADER_SIZE is defined as 2 * sizeof(unsigned int), but in tinymix.c it is added to num_values, which is not a number of bytes.

In addition, TLV_HEADER_SIZE should be based on the actual tlv header size and not hard-coded as it is now.

**Comment by tay10r** [comment]
I've assumed that only byte-sized mixer controls use TLVs, which would make `num_values` equal to the number of bytes. Was this a faulty assumption?

**Comment by simonrules** [comment]
I think it's a fair assumption for bytes - though I didn't make the mental jump to connect the TLV_HEADER_SIZE with bytes only (where num_values == num_bytes). In any case, the TLV_HEADER_SIZE should definitely be based on the actual header size.

**Comment by simonrules** [comment]
This code has now been removed.
