### ISSUE TITLE
Release with cmake support

### ISSUE THREAD

**Issue by ericriff** [tinyalsa/tinyalsa#179]
Hi guys,
 
I'm looking into creating a conan recipe for tinyalsa. This would we way easier if it is built with CMake. Do you guys have an ETA for a release with cmake support?

Thanks!

**Comment by simonrules** [comment]
Check commit 1893950251319724fae9d5b090bccfbc2fbb38d4 - is this what you are looking for?

**Comment by ericriff** [comment]
> Check commit [1893950](https://github.com/tinyalsa/tinyalsa/commit/1893950251319724fae9d5b090bccfbc2fbb38d4) - is this what you are looking for?

I'm asking for a new tag/release which supports CMake. I know that it is already on master.

**Comment by tay10r** [comment]
This is basically the same issue as #154. I've drafted a version 2.0.0 that I wanted to wait on releasing until I could tell if the plugin system is working on Android.
