### ISSUE TITLE
Where to get this libsndcardparser.so

### ISSUE THREAD

**Issue by MrChangMM** [tinyalsa/tinyalsa#195]
I am porting to Android and found the following code：
static struct snd_node *snd_utils_open_dev_node(unsigned int card,
                                                unsigned int device,
                                                int dev_type)
{
    node->dl_hdl = dlopen("libsndcardparser.so", RTLD_NOW);
    if (!node->dl_hdl) {
        goto err_dl_open;
    }
}

but , i can't get this so in project source code.
Where to get this libsndcardparser.so???

**Comment by MrChangMM** [comment]
Hello, Who can answer this question,
Thanks a lot！

**Comment by simonrules** [comment]
You should build without TINYALSA_USES_PLUGINS defined, then tinyalsa will not use the plugin architecture. The library you mentioned will be used at runtime only if the library is built with that define.

I think this could be documented better so I will file a bug.

**Comment by simonrules** [comment]
You should build without TINYALSA_USES_PLUGINS defined, then tinyalsa will
not use the plugin architecture. The library you mentioned will be used at
runtime only if the library is built with that define.

I think this could be documented better so I will file a bug.
