### ISSUE TITLE
pcm_open returns bad_pcm if pcm_prepare fails

### ISSUE THREAD

**Issue by dvdli** [tinyalsa/tinyalsa#197]
In pcm_open in [pcm.c](https://github.com/tinyalsa/tinyalsa/blob/69b9891f995450be8dd8f24dbd39cf1d417fac61/src/pcm.c#L1100-L1102
), we returns the pointer of bad_pcm if pcm_prepare fails. This behavior may not be correct when opening dynamic PCM devices. ALSA SoC driver framework supports to open dynamic PCM devices without connecting them with any backend device. However, we have to connect them with at least one backend device before preparing. Calling preparing function on a dynamic PCM device without connecting any backend device results in failure. 

I suggest to remove these code and let callers call preparing function.

**Comment by pasqualirb** [comment]
This seems to break compatibility with applications that rely on a prepared PCM for IO. Before prepare was done by pcm_open(), it was done [by pcm_writei()](https://github.com/tinyalsa/tinyalsa/blob/1.1.1/src/pcm.c#L691) and [by pcm_readi()](https://github.com/tinyalsa/tinyalsa/blob/1.1.1/src/pcm.c#L747) (indirectly via pcm_start()).

What about calling prepare in the error path of IO functions when state is SETUP? See pasqualirb@1598398bc8c4d35aa4cc72be1deb80aa24c34fa5 (untested).

**Comment by dvdli** [comment]
I agree with you. I'm thinking which solution is better for the applications which don't call the prepare function explicitly in their code. 

In the previous design, tinyalsa library calls the prepare function in the read/write functions. It depends on the preparing flag's and the running flag's status. In the current design, the preparing flag and the running flag were removed and pcm_prepare is called in pcm_open function. However, this might results in a wrong behavior when callers open a dynamic PCM device.

For this problem, one solution is that applications remember their PCM device's state and call the open, prepare and read/write in order. However, the pcm_state is not a public function. Applications can't query the state of the PCM device. 

In my opinion, your solution which TinyALSA calls pcm_prepare according to the state of the PCM device might be a good one. I will try it with the tests.
