### ISSUE TITLE
CMake building error

### ISSUE THREAD

**Issue by Arjentix** [tinyalsa/tinyalsa#199]
I was trying to include tinyalsa in my **C++** project with **CMake**, but I've got this error message:

```
external/tinyalsa/src/pcm.c:626:29: error: overflow in conversion from ‘enum <anonymous>’ to ‘off_t’ {aka ‘long int’} changes value from ‘2147483648’ to ‘-2147483648’ [-Werror=overflow]
                             SNDRV_PCM_MMAP_OFFSET_STATUS);
```

Also it seems like version.sh script works strange, so I am getting this warning message:

```
CMake Warning at external/tinyalsa/CMakeLists.txt:7 (project):
  VERSION keyword not followed by a value or was followed by a value that
  expanded to nothing.
```

It may be important to mention that I am building on **Raspberry Pi**.

My CMakeLists.txt (cutting non relevant info):

```cmake
cmake_minimum_required(VERSION 3.13)
project(my_project)

set(SOURCES
    src/main.cpp
)

add_subdirectory(external/tinyalsa)


add_executable(${CMAKE_PROJECT_NAME} ${SOURCES})

target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE
    external/tinyalsa/include/
)

target_link_libraries (${CMAKE_PROJECT_NAME}
    tinyalsa
)

set_target_properties(${CMAKE_PROJECT_NAME}
    PROPERTIES
    CXX_STANDARD 20
    CXX_STANDARD_REQUIRED ON
    CXX_EXTENSIONS OFF
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/bin"
)

```

**Comment by pasqualirb** [comment]
> I was trying to include tinyalsa in my **C++** project with **CMake**, but I've got this error message:
> 
> ```
> external/tinyalsa/src/pcm.c:626:29: error: overflow in conversion from ‘enum <anonymous>’ to ‘off_t’ {aka ‘long int’} changes value from ‘2147483648’ to ‘-2147483648’ [-Werror=overflow]
>                              SNDRV_PCM_MMAP_OFFSET_STATUS);
> ```

In your environment, off_t is 32 bits. The constant SNDRV_PCM_MMAP_OFFSET_STATUS is equal to 2147483648 (0x80000000) which is greater than the positive limit of a signed 32 bits integer that is 2147483647 (0x7fffffff).

Add `#define _FILE_OFFSET_BITS 64` before any header files, or use `-D_FILE_OFFSET_BITS=64` option of gcc that you can specify in CMake by adding a line containing `add_compile_definitions(_FILE_OFFSET_BITS=64)`. Take a look at the description of `_FILE_OFFSET_BITS` in [feature_test_macros(7) manual page](https://man7.org/linux/man-pages/man7/feature_test_macros.7.html) for more information.

**Comment by E5ten** [comment]
It might be worth adding that define to the various build systems given that without it the build either fails or isn't affected?

**Comment by Arjentix** [comment]
Thi

> > I was trying to include tinyalsa in my **C++** project with **CMake**, but I've got this error message:
> > ```
> > external/tinyalsa/src/pcm.c:626:29: error: overflow in conversion from ‘enum <anonymous>’ to ‘off_t’ {aka ‘long int’} changes value from ‘2147483648’ to ‘-2147483648’ [-Werror=overflow]
> >                              SNDRV_PCM_MMAP_OFFSET_STATUS);
> > ```
> 
> In your environment, off_t is 32 bits. The constant SNDRV_PCM_MMAP_OFFSET_STATUS is equal to 2147483648 (0x80000000) which is greater than the positive limit of a signed 32 bits integer that is 2147483647 (0x7fffffff).
> 
> Add `#define _FILE_OFFSET_BITS 64` before any header files, or use `-D_FILE_OFFSET_BITS=64` option of gcc that you can specify in CMake by adding a line containing `add_compile_definitions(_FILE_OFFSET_BITS=64)`. Take a look at the description of `_FILE_OFFSET_BITS` in [feature_test_macros(7) manual page](https://man7.org/linux/man-pages/man7/feature_test_macros.7.html) for more information.

This worked, thanks!
