### ISSUE TITLE
Consultation on the variable errno in "tinyalsa/pcm.c"

### ISSUE THREAD

**Issue by 13338606692** [tinyalsa/tinyalsa#207]
Variable errno in "tinyalsa/pcm.c" used many times, but did not find the relevant definition, can help explain. thanks!
e.g. in pcm_write:  return oops(pcm, errno, "invalid time stamp");

**Comment by dvdli** [comment]
errno is not defined in the tinyalsa library. It is defined in the header file errno.h in the C standard library. It acts like an integer variable. Functions set an error number to it to let their callers know what errors they get. More info of errno can be found on [wikipedia](https://en.wikipedia.org/wiki/Errno.h).

**Comment by 13338606692** [comment]
thanks!
