### ISSUE TITLE
Why tinyalsa use 10 times buffer size for capture case?

### ISSUE THREAD

**Issue by Sailfy** [tinyalsa/tinyalsa#214]
https://github.com/tinyalsa/tinyalsa/blob/597934fc7c722bc2f9e1f933e1f03a9853159f93/src/pcm.c#L519

It will make alsa driver not do xrun in alsa core even though buffer has been overflowed.
For the accurate timestamp query case, the data will not corresponding to right timestamp at overflow timing.

**Comment by tay10r** [comment]
This is just a default value, it can be changed to something lower by specifying a non-zero `stop_threshold`.

**Comment by Sailfy** [comment]
@tay10r yes, we can make the stop_threshold to be non-zero, but I'm not sure why here use 10 buffer size as default value, as you know, alsa-lib use one buffer size, and the original tinyalsa version is also one buffer size.

**Comment by tay10r** [comment]
@Sailfy it's just always been that way, since about [ten years ago](https://github.com/tinyalsa/tinyalsa/commit/350211381a270fc6f5e02d3a75cbf6bf99152ec8). I'm not entirely sure if anyone is relying on it being that way, so I will cast my vote for leaving it alone.

**Comment by tay10r** [comment]
Closing this, since the question has been answered,
