### ISSUE TITLE
Audio not working in chroot environment

### ISSUE THREAD

**Issue by AlbydST** [tinyalsa/tinyalsa#264]
I recently installed TinyALSA in a minimal Linux chroot environment successfully. It detects my audio device without issues, but, when I try to record some audio with `tinycap test.wav -D 1 -t 10`, and then play it with `tinyplay -D 1 test.wav` I hear nothing. I also hear nothing if I play a file which is proven to contain audio or I take a sample recorded in chroot and try playing it somewhere else. I found out Auto Mute was on and disabled it, but it still didn't work. I also made sure that all necessary file systems like dev, proc and sys are mounted in the chroot environment and the host. Help would be greatly appreciated!

Here is the output of `strace -ff tinycap 10 test.wav -D 1 -t 10`:
https://paste.gentoo.zip/aCXmk1cE

Here is the output of `strace -ff tinyplay 10 test.wav -D 1`:
https://paste.gentoo.zip/0hEa6GVY

Here is the output of `tinymix -D 1 controls`:
https://paste.gentoo.zip/mJAXuuNk

Here is the output of `tinymix -D 1 contents`:
https://paste.gentoo.zip/W0zM25UB
(All settings are maxed because I was testing)

**Comment by stableversion** [comment]
What was the issue?
