### ISSUE TITLE
Bug in mixer_ctl_set_value

### ISSUE THREAD

**Issue by System25** [tinyalsa/tinyalsa#46]
Hi, there is a bug in "mixer_ctl_set_value". I discovered it when I tryed to set with "tinymix" a value to 0 = off. But the value was always 1 = On.

.. code ..
if (value > mixer_ctl_get_range_max(ctl))
        value = mixer_ctl_get_range_max(ctl);
..code..

If "mixer_ctl_get_range_max" returns -22 (EINVAL) then the code set the "value" to "-22".
So, when there is a "boolean" control type, it will allways be "On" and there isn't any error messages.

I think that the code must be something like this:

.. code ..
if (value > mixer_ctl_get_range_max(ctl) && mixer_ctl_get_range_max(ctl)>0)
        value = mixer_ctl_get_range_max(ctl);
..code..

Best regards

**Comment by filaton** [comment]
@tinyalsa Should this issue not be closed? I guess it's fixed by the `switch` [line 415 in `mixer.c`](https://github.com/tinyalsa/tinyalsa/blob/master/mixer.c#L415).

**Comment by tholberton** [comment]
@nonatomiclabs Agreed. Looks like the patch from #40.
