### ISSUE TITLE
tinyplay error unable to open pcm device 

### ISSUE THREAD

**Issue by mohitchauhan** [tinyalsa/tinyalsa#55]
Hi, I am getting this error open("/dev/snd/pcmC0D0p", O_RDONLY)     = -1 EINVAL (Invalid argument)
while using tinyplay on android device samsung galaxy s4 mini, sound card is msm8230-tapan-snd-card.
I am passing input file by matching its configuration with sound card file proc/asound/card0/pcm0p/sub0/hwparam
please tell me reason for this error

**Comment by tinyalsa** [comment]
Could you send me the exact command line you are using to play the file?

tinyplay opens the wav file O_RDONLY but the playback PCM (pcmC0D0p) should
be opened O_RDWR.

Have you checked the kernel log (dmesg)?

Are you using tinyalsa built from github, or the default one included with
the phone?

**Comment by mohitchauhan** [comment]
Hi Simon, Thanks for your reply on this, we solved this issue by setting mixer first.Now its working with the default one included with the phone.
