### ISSUE TITLE
mixer: int_to_percent() doesn't work

### ISSUE THREAD

**Issue by ghost** [tinyalsa/tinyalsa#71]
Hi there,
here is a snippet what [that](https://github.com/tinyalsa/tinyalsa/blob/899cecebd15a7d08781d5f9362ec4bd7cc8863da/mixer.c#L278-L286) function do:

```
#include <stdio.h>

int
main(void)
{
    int n, i = 1;

    n = ((i - 0) / 31) * 100;

    printf("%d\n", n);
    return 0;
}
```

it will print 0 (should be 3).
To fix it you can simply cast `i` to double, float:
`n = (((double)i - 0) / 31) * 100;`

or change to something like this:
`n = (i - 0) * 100 / 31;`

**Comment by at-vol** [comment]
Why closed? Still doesn't work.

**Comment by tay10r** [comment]
I'll look into it. I didn't close it but I'll see what's going on.
