### ISSUE TITLE
tinyplay can't play 24 bits WAV files

### ISSUE THREAD

**Issue by System25** [tinyalsa/tinyalsa#75]
Hi, when you try to play a 24 bits WAV file with tinyplay, it shows an error that says:
 Bitrate is 24 bits, device only supports >= 32 bits

Tracing this problem, I found this happens in:
  check_param(params, PCM_PARAM_SAMPLE_BITS, bits, "Bitrate", " bits");

So, I traced the problem in my Linux kernel, and I think I've found the problem. It seems that 24 bit samples are 32 bits physically. You can see this in:
   http://lxr.free-electrons.com/source/sound/core/pcm_misc.c#L67

And you can see that is the physical sample bits value, the one that is used in "snd_pcm_hw_rule_sample_bits" function:
 http://lxr.free-electrons.com/source/sound/core/pcm_native.c#L1959

This causes that when you call to the SNDRV_PCM_IOCTL_HW_REFINE is 32 the value that is read and not 24.

I think that the easiest workaround to this is to hack the "check_param" function, but this is something that you must decide.

Best regards

**Comment by tay10r** [comment]
Closing this issue, tinyplay has been updated since.

**Comment by sjfricke** [comment]
I just ran into this exact issue trying to play a 32 bit file and it fails [here](https://github.com/tinyalsa/tinyalsa/blob/master/src/pcm.c#L381-L385) and not sure what was updated when this was closed

**Comment by tay10r** [comment]
@sjfricke please open an issue for that. If it's failing at the point you indicated, I also need to see what the output of `tinypcminfo` is that you're using and what the parameters are that you're using in the code that's breaking.
