### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by shiftleftplusone** [tinyalsa/tinyalsa#78]
hello,
there is no discription how to install from a Raspi!
sudo apt-get...?
git clone...?
make...?
make install...?

**Comment by tinyalsa** [comment]
tinyalsa is not currently available by Debian/Ubuntu apt, you'll need to do
a git clone and make.

Let me know if you need help.

**Comment by tholberton** [comment]
@shiftleftplusone This issue is fixed. You can install the project the way you do with most makefiles.
```
make
sudo make install
```

**Comment by shiftleftplusone** [comment]
thank you!
