### ISSUE TITLE
Use tinyalsa to play two audio devices simultaneously with same audio file

### ISSUE THREAD

**Issue by hardiksingh-rathore** [tinyalsa/tinyalsa#81]
Hi, 

I want to use tinyplay with two different device  HDMI tv and audio jack for custom board.
Is it possible to play a video file for  HDMI tv and  audio (from this same video file) with audio jack  ?
(Audio from headphone jack should be synchronous with HDMI video.)

**Comment by tinyalsa** [comment]
Hi, this is dependent on the hardware in question.

Some audio chips support output to multiple different audio sinks (like
headphones, speakers and HDMI) by just adjusting mixer settings. Some
require the audio stream to be sent to many different PCM devices.

tinyplay currently only supports output to a single PCM device. However, it
would be straightforward to modify it to play to multiple PCM devices. For
audio sync, that is a different matter though. You may need to delay the
frames to one stream to get them in sync, and this would be highly
dependent on the HDMI hardware downstream.

Simon
