### ISSUE TITLE
tinymix shouldn't always print the paths

### ISSUE THREAD

**Issue by BradWalker** [tinyalsa/tinyalsa#83]
I work on platforms based on the Qualcomm SnapDragon chip. There can be hundreds of paths on the audio side of this chip.

There was a recent change whereby tinymix will ALWAYS prints the routes/paths for the different ports on ALSA. I consider this to be a regression. It really should only be printed if asked.

In addition, I've modified tinymix to more closely conform to the following:
https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html

Lastly, I removed a redundant errno.h..

**Comment by tholberton** [comment]
@BradWalker I agree with the use of `getopt` and the standard options you added. You need to open a pull request so I can merge them.

**Comment by BradWalker** [comment]
Submitting..

Thanks for the help with this!!
